### PR TITLE
CoDel first pass

### PR DESCRIPTION
**Pull request by drbruced12**
Splice CoDel into the AQM section

### CODE REVIEW

**Comment by brakmo** [comment]
Do we want to mention that Codel is implemented in Linux as a queueing
discipline that can be used to manage egress queue size? It is probably the
largest use of Codel.

The primary issue with Codel as a queueing discipline for TCP is that
packets are dropped at egress instead of, as in most other queueing
disciplines, ingress. When dropping at queue ingress, TCP is notified in
the return value of the write function and TCP will "forget" it sent the
packet (so it will be sent next) and TCP will decrease its cwnd. This means
this "drop" does not count as a packet lost or its resending as a
retransmission. In contrast, dropping from Codel will be interpreted as a
packet loss and TCP will not know to retransmit it until it figures out the
loss with the standard loss detection mechanisms (3 dup acks, timeout, etc.)

**Comment by llpeterson** [comment]
Larry,

Adding a paragraph or two on that point would be good, but here's a
slightly more ambitious idea that might work...

Leave the CoDel section as is (it already mentions the Linux
implementation), and then include a forward reference to a new Section 7.6,
where we take up the general idea of "queuing at the ingress/egress". This
is an opportunity to paint a fairly general picture about the first/last
hop in the network is now in the NIC/IPU (or very bottom of the OS) instead
of a traditional router/switch, where we have an opportunity to manipulate
queues independent of TCP. In addition to revisiting CoDel, we could say a
little bit about your work with eBPF. Does this work?

Larry

**Comment by llpeterson** [comment]
Or -- as is our M.O. -- we could just include a sidebar in 6.3 emphasizing
this new "opportunity" to insert ourselves in the end-to-end path. This
puts a stake in the ground without requiring a ton of additional writing.

Larry

**Comment by drbruced12** [comment]
I like it. Is there a source for the comments on Linux?

Regards, Bruce

**Comment by brakmo** [comment]
Either would work, but I like the idea of also giving Linux references
since it is an open system with wide deployment and most of what we would
say would also apply to other systems.

I think Linux is specially relevant in the context of CC since that is
where most newer ideas are implemented and tested (BIC, Cubic, BBR, etc.).
Also, Linux now supports doing CC in BPF. The standard CC kernel module API
has been ported to BPF and most kernel module CCs are easily ported to the
BPF framework allowing easier deployment of new CCs as well as
modifications to existing CCs. The biggest hurdle in the past to deploying
new CCs has been the need to wait until the relevant kernel is deployed.

- Lawrence

**Comment by llpeterson** [comment]
A statement about "Linux = Reference Implementation" is in Chapter 1, but
it's probably a good point to emphasize throughout the book.

**Comment by llpeterson** [comment]
Larry,

Let me take a shot at a sidebar, and see if it addresses your point.

I'll also look for ways to emphasize the importance of the Linux
implementation. (Let me know if you see any obvious places.)

Larry

**Comment by brakmo** [comment]
The comments on Linux are based on personal experience. I've looked at the
code and had to deal with issues that arose due to codel dropping packets
at egress that looked as if they were dropped in the network. I forgot to
mention that this is one of the reasons why they added ECN marking support
to Codel in Linux, where instead of dropping packets that are queued too
long they can start ECN marking them as having experienced congestion. This
of course is only useful if using CC that support ECN marking such as DCTCP.

**Comment by llpeterson** [comment]
Larry,

I have a couple follow-on questions as I try to write this up...

1) I think of eBPF as a receive-side mechanism, so it's an opportunity to
experiment with the egress queue. But if I want to use it to experiment
with new CC algorithms, I would want the ability to inject my "plugin" on
the send-side. What am I missing? (Is it as simple as eBPF gives me
equivalent access to outgoing traffic?)

2) On-Ramp (now written up as part of 7.1) is interesting because of how it
splits CC into two parts, with the lower-level shim watching the ingress
queue. This sounds like an example of what you're talking about, but I
don't see any mention of the shim being implemented by eBPF in the paper.
Is it, or could it have been?

Larry

**Comment by llpeterson** [comment]
You should have a link to a draft sidebar. Please add your comments. Larry,
I've made some assumptions, denoted by comments that need to be resolved.

Larry

**Comment by llpeterson** [comment]
Sorry for the delay, but I have been traveling for the last 2 days.

>
> 1) I think of eBPF as a receive-side mechanism, so it's an opportunity to
> experiment with the egress queue. But if I want to use it to experiment
> with new CC algorithms, I would want the ability to inject my "plugin" on
> the send-side. What am I missing? (Is it as simple as eBPF gives me
> equivalent access to outgoing traffic?)
>
> eBPF is a general mechanism for safely executing dynamically loaded code
in the kernel. Unlike kernel modules, the code should run on any kernel
that provides the APIs used by the code. In addition, the code is verified
when loaded to insure its safety: can only access kernel memory allowed by
the API, bounded loops, etc.

There is nothing limiting to networking only (although that was the initial
and most common use of eBPF other than tracing), nor to receive side only.
For example, a few years ago I added support for TCP so BPF could be used
to set SYN timeouts based on the IP addresses of the connection, so
connections within a DC could have a small SYN timeout. It could also be
used to set initial cwnd, buffer sizes, etc.

In some ways, eBPF may support the transition to micro-kernel like OSes
that would not suffer the performance penalties that previous
micro-kernels, which depended on protection domains and their costs, had.
In contrast, eBPF uses code analysis to ensure safety. Note that the eBPF
framework translates code in higher level languages to binary so there is
little penalty in using it (other than the cost during load).

Martin Lau, from Facebook, created a framework that supports the use of BPF
for CC (congestion control) functions in Linux's TCP. Here is a link to the
slides to his presentation of his work slides
<https://lpc.events/event/7/contributions/687/attachments/537/1262/BPF_network_tcp-cc-hdr-sk-stg_LPC_2020.pdf>.
I've used this framework to create new CCs. It makes it so easy to deploy
and test new ideas. It also makes it easy to get tracing and logging
information to better understand the dynamics of the algorithm.


> 2) On-Ramp (now written up as part of 7.1) is interesting because of how
> it splits CC into two parts, with the lower-level shim watching the ingress
> queue. This sounds like an example of what you're talking about, but I
> don't see any mention of the shim being implemented by eBPF in the paper.
> Is it, or could it have been?
>

 I am a fan of the main idea of On-Ramp of adding support for handling
transient congestion. The insight that CC has historically focused on
steady state congestion and that there is value in an orthogonal algorithm
for handling transient congestion. Yes, it would be possible to do that in
BPF (although it may require adding some kernel support).

- Lawrence

**Comment by llpeterson** [comment]
That helps. In looking at Martin Lau's slides I was trying to understand
the kernel module API for CC (and its BPF counterpart). If I understand
correctly, the API is defined by the set of functions in struct
tcp_congestion_ops. Is there documentation you can point me at to explain
what each of these functions does... it's not obvious to me why this is the
right set. (I'm trying to build some intuition.)

Larry

**Comment by brakmo** [comment]
> That helps. In looking at Martin Lau's slides I was trying to understand
> the kernel module API for CC (and its BPF counterpart). If I understand
> correctly, the API is defined by the set of functions in struct
> tcp_congestion_ops.


Yes, in addition to the kernel and TCP state accessible from within BPF
(Not all of the TCP state is accessible, and some of what is accessible is
read-only). Historically, state access is added as it is needed.


> Is there documentation you can point me at to explain
> what each of these functions does... it's not obvious to me why this is the
> right set. (I'm trying to build some intuition.)
>

This is Linux, the code is the documentation ;-).  I've added
the declaration of tcp_congestion_ops at the bottom of this email. If it
would be useful for the book, I could write a few pages explaining the API
and giving examples from current CC algorithms.

This is Linux, this is not necessarily the right set of functions. At some
stage, someone decided to modularize CC and they looked at the existing CC
algorithms and where they had functionality. Then they replaced the code
with an indirect function call (for that flow's CC). That early API grew as
needed, adding new functions or modifying the arguments. For example, for
TCP-NV I replaced an integer argument with a struct to pass more values.
For BBR, Google increased TCP state size by 16 bytes, added extra
functionality to the kernel networking code (i.e. not all CC can be
implemented just with the CC API, it may require kernel changes) and wrote
the necessary functions of the API.

- Lawrence

struct tcp_congestion_ops
<https://elixir.bootlin.com/linux/latest/C/ident/tcp_congestion_ops>
{/* fast path fields are put first to fill one cache line */

	/* return slow start threshold (required) */
	u32 <https://elixir.bootlin.com/linux/latest/C/ident/u32> (*ssthresh
<https://elixir.bootlin.com/linux/latest/C/ident/ssthresh>)(struct
sock <https://elixir.bootlin.com/linux/latest/C/ident/sock> *sk);

	/* do new cwnd calculation (required) */
	void (*cong_avoid
<https://elixir.bootlin.com/linux/latest/C/ident/cong_avoid>)(struct
sock <https://elixir.bootlin.com/linux/latest/C/ident/sock> *sk, u32
<https://elixir.bootlin.com/linux/latest/C/ident/u32> ack
<https://elixir.bootlin.com/linux/latest/C/ident/ack>, u32
<https://elixir.bootlin.com/linux/latest/C/ident/u32> acked
<https://elixir.bootlin.com/linux/latest/C/ident/acked>);

	/* call before changing ca_state (optional) */
	void (*set_state
<https://elixir.bootlin.com/linux/latest/C/ident/set_state>)(struct
sock <https://elixir.bootlin.com/linux/latest/C/ident/sock> *sk, u8
<https://elixir.bootlin.com/linux/latest/C/ident/u8> new_state
<https://elixir.bootlin.com/linux/latest/C/ident/new_state>);

	/* call when cwnd event occurs (optional) */
	void (*cwnd_event
<https://elixir.bootlin.com/linux/latest/C/ident/cwnd_event>)(struct
sock <https://elixir.bootlin.com/linux/latest/C/ident/sock> *sk, enum
tcp_ca_event <https://elixir.bootlin.com/linux/latest/C/ident/tcp_ca_event>
ev <https://elixir.bootlin.com/linux/latest/C/ident/ev>);

	/* call when ack arrives (optional) */
	void (*in_ack_event
<https://elixir.bootlin.com/linux/latest/C/ident/in_ack_event>)(struct
sock <https://elixir.bootlin.com/linux/latest/C/ident/sock> *sk, u32
<https://elixir.bootlin.com/linux/latest/C/ident/u32> flags);

	/* hook for packet ack accounting (optional) */
	void (*pkts_acked
<https://elixir.bootlin.com/linux/latest/C/ident/pkts_acked>)(struct
sock <https://elixir.bootlin.com/linux/latest/C/ident/sock> *sk, const
struct ack_sample
<https://elixir.bootlin.com/linux/latest/C/ident/ack_sample> *sample
<https://elixir.bootlin.com/linux/latest/C/ident/sample>);

	/* override sysctl_tcp_min_tso_segs */
	u32 <https://elixir.bootlin.com/linux/latest/C/ident/u32>
(*min_tso_segs <https://elixir.bootlin.com/linux/latest/C/ident/min_tso_segs>)(struct
sock <https://elixir.bootlin.com/linux/latest/C/ident/sock> *sk);

	/* call when packets are delivered to update cwnd and pacing rate,	 *
after all the ca_state processing. (optional)	 */
	void (*cong_control
<https://elixir.bootlin.com/linux/latest/C/ident/cong_control>)(struct
sock <https://elixir.bootlin.com/linux/latest/C/ident/sock> *sk, const
struct rate_sample
<https://elixir.bootlin.com/linux/latest/C/ident/rate_sample> *rs
<https://elixir.bootlin.com/linux/latest/C/ident/rs>);


	/* new value of cwnd after loss (required) */
	u32 <https://elixir.bootlin.com/linux/latest/C/ident/u32>
(*undo_cwnd <https://elixir.bootlin.com/linux/latest/C/ident/undo_cwnd>)(struct
sock <https://elixir.bootlin.com/linux/latest/C/ident/sock> *sk);
	/* returns the multiplier used in tcp_sndbuf_expand (optional) */
	u32 <https://elixir.bootlin.com/linux/latest/C/ident/u32>
(*sndbuf_expand
<https://elixir.bootlin.com/linux/latest/C/ident/sndbuf_expand>)(struct
sock <https://elixir.bootlin.com/linux/latest/C/ident/sock> *sk);
/* control/slow paths put last */
	/* get info for inet_diag (optional) */
	size_t <https://elixir.bootlin.com/linux/latest/C/ident/size_t>
(*get_info <https://elixir.bootlin.com/linux/latest/C/ident/get_info>)(struct
sock <https://elixir.bootlin.com/linux/latest/C/ident/sock> *sk, u32
<https://elixir.bootlin.com/linux/latest/C/ident/u32> ext
<https://elixir.bootlin.com/linux/latest/C/ident/ext>, int *attr,
			   union tcp_cc_info
<https://elixir.bootlin.com/linux/latest/C/ident/tcp_cc_info> *info);

	char 			name[TCP_CA_NAME_MAX
<https://elixir.bootlin.com/linux/latest/C/ident/TCP_CA_NAME_MAX>];
	struct module <https://elixir.bootlin.com/linux/latest/C/ident/module>		*owner
<https://elixir.bootlin.com/linux/latest/C/ident/owner>;
	struct list_head
<https://elixir.bootlin.com/linux/latest/C/ident/list_head>	list;
	u32 <https://elixir.bootlin.com/linux/latest/C/ident/u32>			key
<https://elixir.bootlin.com/linux/latest/C/ident/key>;
	u32 <https://elixir.bootlin.com/linux/latest/C/ident/u32>			flags;

	/* initialize private data (optional) */
	void (*init <https://elixir.bootlin.com/linux/latest/C/ident/init>)(struct
sock <https://elixir.bootlin.com/linux/latest/C/ident/sock> *sk);
	/* cleanup private data  (optional) */
	void (*release
<https://elixir.bootlin.com/linux/latest/C/ident/release>)(struct sock
<https://elixir.bootlin.com/linux/latest/C/ident/sock> *sk);}
____cacheline_aligned_in_smp
<https://elixir.bootlin.com/linux/latest/C/ident/____cacheline_aligned_in_smp>;

struct ack_sample <https://elixir.bootlin.com/linux/latest/C/ident/ack_sample> {
	u32 <https://elixir.bootlin.com/linux/latest/C/ident/u32> pkts_acked
<https://elixir.bootlin.com/linux/latest/C/ident/pkts_acked>;
	s32 <https://elixir.bootlin.com/linux/latest/C/ident/s32> rtt_us
<https://elixir.bootlin.com/linux/latest/C/ident/rtt_us>;
	u32 <https://elixir.bootlin.com/linux/latest/C/ident/u32> in_flight
<https://elixir.bootlin.com/linux/latest/C/ident/in_flight>;};

/* A rate sample measures the number of (original/retransmitted) data
* packets delivered "delivered" over an interval of time
"interval_us". * The tcp_rate.c code fills in the rate sample, and
congestion * control modules that define a cong_control function to
run at the end * of ACK processing can optionally chose to consult
this sample when * setting cwnd and pacing rate. * A sample is invalid
if "delivered" or "interval_us" is negative. */struct rate_sample
<https://elixir.bootlin.com/linux/latest/C/ident/rate_sample> {
	u64 <https://elixir.bootlin.com/linux/latest/C/ident/u64>
prior_mstamp <https://elixir.bootlin.com/linux/latest/C/ident/prior_mstamp>;
/* starting timestamp for interval */
	u32 <https://elixir.bootlin.com/linux/latest/C/ident/u32>
prior_delivered
<https://elixir.bootlin.com/linux/latest/C/ident/prior_delivered>;	/*
tp->delivered at "prior_mstamp" */
	u32 <https://elixir.bootlin.com/linux/latest/C/ident/u32>
prior_delivered_ce
<https://elixir.bootlin.com/linux/latest/C/ident/prior_delivered_ce>;/*
tp->delivered_ce at "prior_mstamp" */
	s32 <https://elixir.bootlin.com/linux/latest/C/ident/s32>  delivered
<https://elixir.bootlin.com/linux/latest/C/ident/delivered>;		/*
number of packets delivered over interval */
	s32 <https://elixir.bootlin.com/linux/latest/C/ident/s32>
delivered_ce <https://elixir.bootlin.com/linux/latest/C/ident/delivered_ce>;	/*
number of packets delivered w/ CE marks*/
	long interval_us
<https://elixir.bootlin.com/linux/latest/C/ident/interval_us>;	/* time
for tp->delivered to incr "delivered" */
	u32 <https://elixir.bootlin.com/linux/latest/C/ident/u32>
snd_interval_us
<https://elixir.bootlin.com/linux/latest/C/ident/snd_interval_us>;	/*
snd interval for delivered packets */
	u32 <https://elixir.bootlin.com/linux/latest/C/ident/u32>
rcv_interval_us
<https://elixir.bootlin.com/linux/latest/C/ident/rcv_interval_us>;	/*
rcv interval for delivered packets */
	long rtt_us <https://elixir.bootlin.com/linux/latest/C/ident/rtt_us>;		/*
RTT of last (S)ACKed packet (or -1) */
	int  losses <https://elixir.bootlin.com/linux/latest/C/ident/losses>;		/*
number of packets marked lost upon ACK */
	u32 <https://elixir.bootlin.com/linux/latest/C/ident/u32>
acked_sacked <https://elixir.bootlin.com/linux/latest/C/ident/acked_sacked>;	/*
number of packets newly (S)ACKed upon ACK */
	u32 <https://elixir.bootlin.com/linux/latest/C/ident/u32>
prior_in_flight
<https://elixir.bootlin.com/linux/latest/C/ident/prior_in_flight>;	/*
in flight before this ACK */
	bool <https://elixir.bootlin.com/linux/latest/C/ident/bool>
is_app_limited <https://elixir.bootlin.com/linux/latest/C/ident/is_app_limited>;	/*
is sample from packet with bubble in pipe? */
	bool <https://elixir.bootlin.com/linux/latest/C/ident/bool>
is_retrans <https://elixir.bootlin.com/linux/latest/C/ident/is_retrans>;	/*
is sample from retransmission? */
	bool <https://elixir.bootlin.com/linux/latest/C/ident/bool>
is_ack_delayed <https://elixir.bootlin.com/linux/latest/C/ident/is_ack_delayed>;	/*
is this (likely) a delayed ACK? */};

**Comment by llpeterson** [comment]
Larry,

I can see where a description (and examples) of the CC module API could be
a really valuable addition to the book. But it also feels like a pretty
heavy lift, especially if we try to go beyond just documenting the API, and
trying to also explain/rationalize it (which is our M.O.). Here's my
proposal... we tie up the current loose ends (most notably, the
ingress/egress writeup that started this thread), and then start working on
a thorough implementation chapter for the next release. I don't know if
you've followed the comments on the Google Doc, but I'm going to expand the
sidebar into a full section, which briefly mentions the API and BPF (and
will include one or two links). Does that work?

It would also be great to hear if you see any glaring errors or
low-hanging-fruit in what we've written.

Larry

**Comment by llpeterson** [comment]
I think I've resolved my open issues. See
https://github.com/SystemsApproach/tcpcc/commit/bde5a245b4533640fabc241e840449433f0f86ed
for the latest version (now a section rather than a sidebar).

Larry

**Pull request merged**
