### PR TITLE
Typo fixes in intro and design chapters.

### PR DESCRIPTION
**Pull request by gmichelo**
Great book. I am still reading it but I'd like to provide the fixes I've found so far.

I believe the second network topology is a LAN as it has only 10ms of RTT. Also, Figure 13 refers to the first two topologies on the list.

### CODE REVIEW

**Review by llpeterson — CHANGES_REQUESTED** [review]
Thanks! The fine --> find correction is a good one. It's admittedly a gray area, but the intent on the optional 10ms delay is that it represents a WAN (rather than a LAN) topology.

**Review by llpeterson — CHANGES_REQUESTED** [review]
The "extensions" typo is a good catch, but "means" is right: "...provides a means to..." = "...provides a way to..." Keep 'em coming.

**Comment by llpeterson** [comment]
I'm going to go ahead and accept this, and then back out of the "means" change. You've definitely earned your free copy of the book.

**Comment by gmichelo** [comment]
Thank you very much! I might open new PRs if I find something else. Let me know if there is any deadline for the printing of the book.

**Pull request merged**
